services:
  db-test:
    container_name: db-test
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-test
    environment:
      - POSTGRES_PASSWORD=isel
      - POSTGRES_USER=isel
      - POSTGRES_DB=iseldawdev
    ports:
      - "5432:5432"
  prod-db:
    container_name: prod-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-test
    environment:
      - POSTGRES_PASSWORD=isel
      - POSTGRES_USER=isel
      - POSTGRES_DB=iseldaw
    ports:
      - "5433:5432"
  api:
    container_name: api
    depends_on:
      - prod-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    environment:
        - DB_URL=jdbc:postgresql://prod-db:5432/iseldaw?user=isel&password=isel
        - POSTGRES_PASSWORD=isel
        - POSTGRES_USER=isel
        - POSTGRES_DB=iseldaw
    ports:
        - "8080:8080"