services:

  db-test:
    container_name: db-test
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-test
    environment:
      - POSTGRES_PASSWORD=isel
      - POSTGRES_USER=isel
      - POSTGRES_DB=iseldawdev
    ports:
      - "5432:5432"

  prod-db:
    container_name: prod-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-test
    environment:
      - POSTGRES_PASSWORD=isel
      - POSTGRES_USER=isel
      - POSTGRES_DB=iseldaw
    ports:
      - "5433:5432"

  deploy-api:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-jvm
    environment:
      - DB_URL=jdbc:postgresql://prod-db:5432/iseldaw?user=isel&password=isel
      - PORT=8080
    depends_on:
      - prod-db

  nginx:
    container_name: im-nginx
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile-nginx
    ports:
      - "8080:8080"
    depends_on:
      - deploy-api

  deploy:
    container_name: deploy
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-ts
    ports:
      - "8000:8000"
    environment:
      - API_CONTEXT=/api
      - API_TARGET=http://nginx:8080
    depends_on:
      - nginx