services:
  db-test:
    container_name: db-test
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - POSTGRES_PASSWORD=isel
      - POSTGRES_USER=isel
      - POSTGRES_DB=iseldawdev
    ports:
      - "5432:5432"
  production-db:
    container_name: production-db
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - POSTGRES_PASSWORD=isel
      - POSTGRES_USER=isel
      - POSTGRES_DB=iseldaw
    ports:
      - "5433:5432"